theme: jekyll-theme-cayman
title: tales-of-an-absurdist
description: absurd blogs on AI and everything that i find interesting.
author: yugant-ghimire
url: https://yugant10-commits.github.io/
baseurl: ""

# Build settings
markdown: kramdown
emote_theme: jekyll/minima  # Adding this for a default theme
theme: minima   
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-feed
  - jekyll-seo-tag